name: Matrix Demo
on: push
jobs:
  build:
    strategy:
      matrix:
        node-version: [16,18,20]
        operating_system: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Get code
        uses: actions/checkoutV3
      - name: Install Nodejs
        uses: actions/setup-nodeV3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
